import turtle
def draw_circle(x_cor, y_cor, radius, pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.setx(x_cor)
    turtle.sety(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(radius)
    turtle.penup()
    turtle.end_fill()
    return print(turtle.isdown(), turtle.heading(), turtle.xcor(), turtle.ycor()) # state of the turtle


def draw_equal_triangle(x_cor, y_cor, size, pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.sety(x_cor)
    turtle.setx(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.penup()
    turtle.end_fill()
def draw_rectangle(x_cor, y_cor, width, height, pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.sety(x_cor)
    turtle.setx(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.penup()
    turtle.end_fill()
def draw_composite_shape(x_cor, y_cor, x_cor2, y_cor2,width, height, size,pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.sety(x_cor)
    turtle.setx(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.penup()
    turtle.end_fill()
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor("black")
    turtle.fillcolor("orange")
    turtle.sety(x_cor2)
    turtle.setx(y_cor2)
    turtle.begin_fill()
    turtle.pendown()
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.penup()
    turtle.end_fill()
    

def main():
    # draw_circle(20, 30, 50, "yellow", "purple")
    # draw_equal_triangle(20,20,60,"red","blue")
    # draw_rectangle(50, 60, 100, 70, "pink", "red")
    draw_composite_shape(50, 80, 100, 80, 100, 50,100,"pink", "red")
    input("Press enter to continue")
main()