"""
This program draws a skyline
Alex Lalama
"""
import turtle
def draw_rectangle(x_cor, y_cor, width, height, pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.sety(x_cor)
    turtle.setx(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(height)
    turtle.left(90)
    turtle.penup()
    turtle.end_fill()
def draw_equal_triangle(x_cor, y_cor, size, pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.sety(x_cor)
    turtle.setx(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.forward(size)
    turtle.left(120)
    turtle.penup()
    turtle.end_fill()

def draw_circle(x_cor, y_cor, radius, pencolor, fillcolor):
    turtle.penup()
    turtle.pensize(5)
    turtle.pencolor(pencolor)
    turtle.fillcolor(fillcolor)
    turtle.setx(x_cor)
    turtle.sety(y_cor)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(radius)
    turtle.penup()
    turtle.end_fill()
    

def main():
    turtle.speed(100)
    draw_rectangle(-280, -340, 680, 200, "brown", "brown")
    draw_rectangle(-80, -340, 680, 380, "blue", "blue")
    draw_equal_triangle(-80, -280, 100, "gray", "gray")
    draw_equal_triangle(-80, -200, 200, "gray", "gray")
    draw_equal_triangle(-80, 0, 300, "gray", "gray")
    draw_circle(100, 200, 40, "white", "white")
    draw_circle(-100, 200, 40, "lightblue", "lightblue")
    draw_circle(-130, 170, 40, "lightblue", "lightblue")
    draw_circle(-80, 160, 40, "lightblue", "lightblue")
    # draw_circle(100, 200, 40, "white", "white")
    # draw_circle(100, 200, 40, "white", "white")
    # draw_circle(100, 200, 40, "white", "white")
    turtle.setx(-280)
    turtle.sety(-340)
    input("Press enter to continue")
main()