adj1 = input ("Enter a adjective: ")
adj2 = input("Enter a adjective: ")
type_of_bird = input("Enter a type of bird: ")
room_in_house = input("Enter a room in a house: ")
verb_past = input("Enter a past tensed verb: ")
verb = input("Enter a verb: ")
relative = input("Enter a relative's name: ")
noun = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
verb_ing =input("Enter a verb ending in 'ing': ")


print("It was a ", adj1, ", cold November day.", end="",sep="")
print(" I woke up to the ",adj2 ," smell of ", type_of_bird, sep="")
print("roasting in the",room_in_house ,"downstairs. I ", verb_past, end='') 
print(" down the stairs to see if I could help") 
print(verb, "the dinner.", end="")
print(" My mom said, 'See if ", relative, " needs a fresh ", noun, ".'",sep="")
print("So I carried a tray of glasses full of", liquid, "into the ", end="")
print(verb_ing, "room.")