import turtle
def draw_star(length):
    turtle.pendown()
    turtle.forward(length)
    turtle.left(72)
    turtle.forward(length)
    turtle.right(144)
    turtle.forward(length)
    turtle.left(72)
    turtle.forward(length)
    turtle.right(144)
    turtle.forward(length)
    turtle.left(72)
    turtle.forward(length)
    turtle.right(144)
    turtle.forward(length)
    turtle.left(72)
    turtle.forward(length)
    turtle.right(144)
    turtle.forward(length)
    turtle.left(72)
    turtle.forward(length)
    turtle.penup()
def main():
    draw_star(50)
    input("Press enter to continu")
main()